### ISSUE TITLE
Unable to blacklist Controller Action

### ISSUE THREAD

**Issue by zacksiri** [timberio/timber-elixir#253]
I've installed Timber 2.6.1 in my application.

I've also configured the blacklisting as such:

``` elixir
config :timber, Timber.Integrations.PhoenixInstrumenter,
  controller_actions_blacklist: [
    {Studio.Web.HealthController, :show}
  ]
```

When I make a request to the `/health` route I still get response logged in Timber.

I also tried using the Plug approach it still logs health checks.

**Comment by binarylogic** [comment]
Hey @zacksiri thanks for reporting. We're going to try and take a look this week.

**Comment by tlvenn** [comment]
Any news on this guys ? I have the same issue

**Comment by DavidAntaramian** [comment]
@tlvenn and @zacksiri Sorry for the delay. Could you please let me know what version of Phoenix you're running? Thank you

**Comment by DavidAntaramian** [comment]
I just want to confirm that you're both following the directions in this documentations: https://timber.io/docs/languages/elixir/configuration/blacklisting-routes

My hunch is that you are seeing the Plug logs still, and the first half of the document shows how to suppress those.

If that doesn't work, please follow up :)

**Comment by tlvenn** [comment]
Using Phoenix 1.3 here and your hunch is wrong ;) I have properly filtered out plug logs already and it's the phoenix log I am still seeing for the health check controller.

**Comment by DavidAntaramian** [comment]
@tlvenn Thanks for following up! I haven't been able to reproduce this in a new application using Phoenix 1.3.2 on Elixir 1.6.4 and Erlang 20.3.1 with package version 2.6.1. If you start a new application, are you able to reproduce the problem? I'm looking for a minimum viable example to see where things go wrong.

**Comment by binarylogic** [comment]
@tlvenn are you still experiencing this? If so, we'd love to resolve it. Please re-open if you're still experiencing this. Thanks.

**Comment by ryanwinchester** [comment]
@binarylogic I am experiencing this right now and it's driving me nuts.

**Comment by binarylogic** [comment]
Hey @ryanwinchester, we recently released `1.1.0` of our `timber-elixir-phoenix` library which should resolve this. The specific commits are:

* https://github.com/timberio/timber-elixir-phoenix/commit/f70d3125612ada459e261dda11b027cb72a64cdb
* https://github.com/timberio/timber-elixir-phoenix/commit/4aaa4768631d7fe8fce508f835bcbb76512a26a1

Let me know if that doesn't resolve your issue. We're happy to help.

**Comment by ryanwinchester** [comment]
@binarylogic thanks. It would help if you published that version to hex, too :)

**Comment by binarylogic** [comment]
Hey @ryanwinchester, apologies, I meant `1.0.1`. It's available here: https://hex.pm/packages/timber_phoenix/1.0.1

**Comment by ryanwinchester** [comment]
@binarylogic I am using 1.0.1 :(

**Comment by mitchellhenke** [comment]
@binarylogic Yep, I see the issue now 🤦‍♂️

There was an error in the docs that I've fixed here: https://github.com/timberio/timber-elixir-phoenix/pull/7

@ryanwinchester 
Applying this patch should fix it:
```diff
-config :timber_phoenix, Timber.Phoenix,
+config :timber_phoenix,
  parsed_controller_actions_blacklist: MapSet.new([
    {MyAppWeb.StatusController, nil}
  ])
```

**Comment by binarylogic** [comment]
Ah! Glad we figured it out.

**Comment by ryanwinchester** [comment]
I've updated the config and still getting the status logs :(

**Comment by ryanwinchester** [comment]
I removed `Timber.Plug.Event` and got it down to 2 lines.
Removing `Timber.Plug.HTTPContext` still had 2 lines but less info.
